In [27]:
import pandas as pd

In [28]:
bk = pd.read_csv('C:/Users/shubh/Pranjal Sir class/Logistic/svmfile.csv')

In [29]:
bk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             41188 non-null  int64  
 1   job             41188 non-null  object 
 2   marital         41188 non-null  object 
 3   education       41188 non-null  object 
 4   default         41188 non-null  object 
 5   housing         41188 non-null  object 
 6   loan            41188 non-null  object 
 7   contact         41188 non-null  object 
 8   month           41188 non-null  object 
 9   day_of_week     41188 non-null  object 
 10  duration        41188 non-null  int64  
 11  campaign        41188 non-null  int64  
 12  pdays           41188 non-null  int64  
 13  previous        41188 non-null  int64  
 14  poutcome        41188 non-null  object 
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null 

In [30]:
bk.head()

age        job  marital    education  default housing loan    contact  \
0   56  housemaid  married     basic.4y       no      no   no  telephone   
1   57   services  married  high.school  unknown      no   no  telephone   
2   37   services  married  high.school       no     yes   no  telephone   
3   40     admin.  married     basic.6y       no      no   no  telephone   
4   56   services  married  high.school       no      no  yes  telephone   

  month day_of_week  ...  campaign  pdays  previous     poutcome emp.var.rate  \
0   may         mon  ...         1    999         0  nonexistent          1.1   
1   may         mon  ...         1    999         0  nonexistent          1.1   
2   may         mon  ...         1    999         0  nonexistent          1.1   
3   may         mon  ...         1    999         0  nonexistent          1.1   
4   may         mon  ...         1    999         0  nonexistent          1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
0          93.994          -36.4      4.857       5191.0  no  
1          93.994          -36.4      4.857       5191.0  no  
2          93.994          -36.4      4.857       5191.0  no  
3          93.994          -36.4      4.857       5191.0  no  
4          93.994          -36.4      4.857       5191.0  no  

[5 rows x 21 columns]

In [31]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [32]:
bk.job = le.fit_transform(bk.job)
bk.marital = le.fit_transform(bk.marital)


In [33]:
bk.education.value_counts()

university.degree      12168
high.school             9515
basic.9y                6045
professional.course     5243
basic.4y                4176
basic.6y                2292
unknown                 1731
illiterate                18
Name: education, dtype: int64

In [34]:
bk.education  = bk.education.replace({'unknown':0, 'illiterate':0,
                                     'basic.4y':1, 'basic.6y':2,
                                     'basic.9y':3, 'high.school':4,
                                     'professional.course':5,'university.degree':6})

In [35]:
bk.education.value_counts()

6    12168
4     9515
3     6045
5     5243
1     4176
2     2292
0     1749
Name: education, dtype: int64

In [36]:
bk.loan.value_counts()

no         33950
yes         6248
unknown      990
Name: loan, dtype: int64

In [37]:
bk.default = bk.default.replace({'no':0,'unknown':1,'yes':2})

In [38]:
bk.housing = bk.housing.replace({'no':0,'unknown':1,'yes':2})

In [39]:
bk.loan = bk.loan.replace({'no':0,'unknown':1,'yes':2})

In [40]:
bk.month.value_counts()

may    13769
jul     7174
aug     6178
jun     5318
nov     4101
apr     2632
oct      718
sep      570
mar      546
dec      182
Name: month, dtype: int64

In [41]:
bk.contact = le.fit_transform(bk.contact)

In [42]:
bk.month= bk.month.replace({'may':5,'jul':7,'aug':8,'jun':6,'nov':11,'apr':4,'oct':10,'sep':9,'mar':3,'dec':12})

In [43]:
bk.poutcome.value_counts()

nonexistent    35563
failure         4252
success         1373
Name: poutcome, dtype: int64

In [44]:
bk.day_of_week = bk.day_of_week.replace({'mon':1, 'tue':2, 'wed':3,'thu':4,'fri':5})

In [45]:
bk.poutcome = bk.poutcome.replace({'nonexistent':0,'failure':1,'success':2})

In [46]:
bk.y = bk.y.replace({'no':0,'yes':1})

In [47]:
bk.head()

age  job  marital  education  default  housing  loan  contact  month  \
0   56    3        1          1        0        0     0        1      5   
1   57    7        1          4        1        0     0        1      5   
2   37    7        1          4        0        2     0        1      5   
3   40    0        1          2        0        0     0        1      5   
4   56    7        1          4        0        0     2        1      5   

   day_of_week  ...  campaign  pdays  previous  poutcome  emp.var.rate  \
0            1  ...         1    999         0         0           1.1   
1            1  ...         1    999         0         0           1.1   
2            1  ...         1    999         0         0           1.1   
3            1  ...         1    999         0         0           1.1   
4            1  ...         1    999         0         0           1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed  y  
0          93.994          -36.4      4.857       5191.0  0  
1          93.994          -36.4      4.857       5191.0  0  
2          93.994          -36.4      4.857       5191.0  0  
3          93.994          -36.4      4.857       5191.0  0  
4          93.994          -36.4      4.857       5191.0  0  

[5 rows x 21 columns]

In [48]:
from sklearn.model_selection import train_test_split
bk_train, bk_test = train_test_split(bk, test_size = 0.2)
bk1 = bk_train[bk_train.y == 1]
bk_train = pd.concat([bk_train, bk1, bk1, bk1])

bk_train_x = bk_train.iloc[:,0:-1]
bk_train_y = bk_train.iloc[:,-1]

bk_test_x = bk_test.iloc[:,0:-1]
bk_test_y = bk_test.iloc[:,-1]

In [49]:

bk1.shape

(3733, 21)

In [50]:
bk1.y.value_counts()

1    3733
Name: y, dtype: int64

In [51]:
bk_train_x

age  job  marital  education  default  housing  loan  contact  month  \
19382   42    4        1          4        0        0     0        0      8   
19101   33    9        1          6        0        2     0        0      8   
40840   32    0        2          6        0        2     0        0      9   
18452   32    0        1          6        0        2     0        0      7   
8001    42    5        1          3        1        0     0        1      6   
...    ...  ...      ...        ...      ...      ...   ...      ...    ...   
16273   33    7        2          4        1        2     0        0      7   
40364   27    8        2          6        0        2     0        0      8   
39659   28    0        2          4        0        2     0        0      5   
30565   58    0        1          6        0        2     2        0      5   
39115   73    5        0          4        0        2     0        0     12   

       day_of_week  duration  campaign  pdays  previous  poutcome  \
19382            3       588         3    999         0         0   
19101            2       316         2    999         0         0   
40840            1       990         4    999         0         0   
18452            4       129         1    999         0         0   
8001             1        67         2    999         0         0   
...            ...       ...       ...    ...       ...       ...   
16273            2       560         2    999         0         0   
40364            3       651         1      0         3         2   
39659            4       263         1      6         1         2   
30565            1       353         2    999         0         0   
39115            2       284         1    999         0         0   

       emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  nr.employed  
19382           1.4          93.444          -36.1      4.967       5228.1  
19101           1.4          93.444          -36.1      4.968       5228.1  
40840          -1.1          94.199          -37.5      0.879       4963.6  
18452           1.4          93.918          -42.7      4.968       5228.1  
8001            1.4          94.465          -41.8      4.865       5228.1  
...             ...             ...            ...        ...          ...  
16273           1.4          93.918          -42.7      4.961       5228.1  
40364          -1.7          94.027          -38.3      0.900       4991.6  
39659          -1.8          93.876          -40.0      0.683       5008.7  
30565          -1.8          92.893          -46.2      1.354       5099.1  
39115          -3.0          92.713          -33.0      0.707       5023.5  

[44149 rows x 20 columns]

In [62]:
from sklearn.model_selection import GridSearchCV
search_dict = {'kernel' : ('linear')}

from sklearn.svm import SVC
svc_bk = SVC(kernel = 'linear')
grid_svc = GridSearchCV(svc_bk,  param_grid = search_dict)
svm_bk.fit(bk_train_x, bk_train_y)

ValueError: Parameter grid for parameter (kernel) needs to be a list or numpy array, but got (<class 'str'>). Single values need to be wrapped in a list with one element.

In [55]:
grid_svc.best_params_

NameError: name 'grid_svc' is not defined

In [ ]:
pred_svm = grid_svc.predict(bk_test_x)

In [ ]:
from sklearn.metrics import confusion_matrix
tab_svm = confusion_matrix(pred_svm, bk_test_y)
tab_svm

In [ ]:
# before over Sampling
# array([[7067,  538],
#        [ 260,  373]], dtype=int64)

# ADA BOOST

In [63]:
from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import AdaBoostClassifier

In [71]:
dt = DecisionTreeClassifier(criterion='entropy')

In [72]:
abc = AdaBoostClassifier(dt, n_estimators=10)

In [73]:
abc.fit(bk_train_x, bk_train_y)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(criterion='entropy'),
                   n_estimators=10)

In [74]:
pred_boost = abc.predict(bk_test_x)

In [75]:
from sklearn.metrics import confusion_matrix

tab_boost = confusion_matrix(pred_boost, bk_test_y)
tab_boost

array([[6883,  449],
       [ 448,  458]], dtype=int64)

In [76]:
abc.feature_importances_

array([0.07568992, 0.03546495, 0.01218032, 0.02925148, 0.00680892,
       0.01276245, 0.00868098, 0.00545453, 0.04898227, 0.02954769,
       0.37713823, 0.03221433, 0.0132035 , 0.0065553 , 0.00428626,
       0.0291634 , 0.01121266, 0.00797779, 0.07856796, 0.17485706])

In [77]:
df_imp = pd.DataFrame({'Feature':bk_train_x.columns, 'Importance':abc.feature_importances_})

In [79]:
df_imp.sort_values('Importance', ascending=False)

Feature  Importance
10        duration    0.377138
19     nr.employed    0.174857
18       euribor3m    0.078568
0              age    0.075690
8            month    0.048982
1              job    0.035465
11        campaign    0.032214
9      day_of_week    0.029548
3        education    0.029251
15    emp.var.rate    0.029163
12           pdays    0.013204
5          housing    0.012762
2          marital    0.012180
16  cons.price.idx    0.011213
6             loan    0.008681
17   cons.conf.idx    0.007978
4          default    0.006809
13        previous    0.006555
7          contact    0.005455
14        poutcome    0.004286

In [80]:
from sklearn.ensemble import RandomForestClassifier

from sklearn.ensemble import AdaBoostClassifier

In [81]:
rfc = RandomForestClassifier()

In [82]:
abc_rf = AdaBoostClassifier(rfc)

In [84]:
abc_rf.fit(bk_train_x, bk_train_y)

AdaBoostClassifier(base_estimator=RandomForestClassifier())

In [86]:
pred12 = abc_rf.predict(bk_test_x)

In [87]:
tab12 = confusion_matrix(pred12, bk_test_y)

In [88]:
tab12

array([[6966,  329],
       [ 365,  578]], dtype=int64)