In [1]:
import pandas as pd
import numpy as np

In [2]:
ctg = pd.read_csv(r'CTG.csv')

In [3]:
ctg.head()

LB     AC   FM  NSP
0  120  0.000  0.0    2
1  132  0.006  0.0    1
2  133  0.003  0.0    1
3  134  0.003  0.0    1
4  132  0.007  0.0    1

In [4]:
ctg.isnull().sum()

LB     0
AC     0
FM     0
NSP    0
dtype: int64

In [5]:
ctg.NSP.value_counts()

1    1655
2     295
3     176
Name: NSP, dtype: int64

In [6]:
ctg.shape

(2126, 4)

In [7]:
print('% rec for class 1 is', np.round(1655 *100/2126))
print('% rec for class 2 is', np.round(295 *100/2126))
print('% rec for class 3 is', np.round(176 *100/2126))

% rec for class 1 is 78.0
% rec for class 2 is 14.0
% rec for class 3 is 8.0


In [8]:
from sklearn.model_selection import train_test_split

In [9]:
ctg_train, ctg_test = train_test_split(ctg, test_size = 0.2)

In [10]:
ctg_train_x = ctg_train.iloc[:,[0,1,2]]
ctg_train_y = ctg_train.iloc[:,3]

ctg_test_x = ctg_train.iloc[:,[0,1,2]]
ctg_test_y = ctg_train.iloc[:,3]

In [11]:
print(ctg_train_x.shape)
print(ctg_train_y.shape)
print(ctg_test_x.shape)
print(ctg_test_y.shape)


(1700, 3)
(1700,)
(1700, 3)
(1700,)


In [13]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()

In [22]:
score_dtree = cross_val_score(dtree, ctg_train_x, ctg_train_y, cv= 10)

<IPython.core.display.Javascript object>

In [23]:
score_dtree

array([0.88235294, 0.78823529, 0.83529412, 0.85294118, 0.82352941,
       0.86470588, 0.84705882, 0.84705882, 0.81176471, 0.78235294])

In [24]:
list(score_dtree)

[0.8823529411764706,
 0.788235294117647,
 0.8352941176470589,
 0.8529411764705882,
 0.8235294117647058,
 0.8647058823529412,
 0.8470588235294118,
 0.8470588235294118,
 0.8117647058823529,
 0.7823529411764706]

In [25]:
score_dtree.max()

0.8823529411764706

In [26]:
score_dtree.min()

0.7823529411764706

In [27]:
score_dtree.mean()

0.8335294117647057

In [28]:
score_dtree.std()

0.030571262259261843

In [29]:
from sklearn.ensemble import RandomForestClassifier
rand = RandomForestClassifier()

In [42]:
score_rand = cross_val_score(rand, ctg_train_x, ctg_train_y, cv= 10)

<IPython.core.display.Javascript object>

In [43]:
score_rand

array([0.87058824, 0.78823529, 0.84117647, 0.84705882, 0.81764706,
       0.87647059, 0.84705882, 0.87058824, 0.79411765, 0.78823529])

In [46]:
score_rand.mean()

0.8341176470588236

In [47]:
score_rand.min()

0.788235294117647

In [48]:
score_rand.max()

0.8764705882352941

In [35]:
from sklearn.linear_model import LinearRegression
lin = LinearRegression()

In [50]:
score_lin = cross_val_score(lin, ctg_train_x, ctg_train_y, cv= 10)

<IPython.core.display.Javascript object>

In [40]:
score_lin

array([0.19538618, 0.15046436, 0.22593753, 0.15792103, 0.18443732,
       0.10258384, 0.10620785, 0.18893469, 0.16582401, 0.08756216])

In [41]:
score_lin.mean()

0.15652589731138716